apiVersion: v1
kind: Service
metadata:
  name: appointments-frontend
  namespace: appointments
spec:
  selector:
    app: appointments-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
  type: ClusterIP
