name: Frontend Continuous Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  deploy:
    needs: ci
    runs-on: [self-hosted, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Minikube and Build Docker Image
        run: |
          minikube start
          eval $(minikube -p minikube docker-env)
          docker build -t appointments-frontend:${{ github.ref_name }} .

      - name: Deploy to Minikube
        run: |
          sed -i 's|appointments-frontend:${TAG}|appointments-frontend:${{ github.ref_name }}|' k8s/deployment.yaml
          kubectl create namespace appointments || true
          kubectl apply -f k8s/deployment.yaml -n appointments
          kubectl apply -f k8s/service.yaml -n appointments
          kubectl rollout status deployment/appointments-frontend -n appointments

      - name: Verify Deployment
        run: |
          kubectl get pods -n appointments
          kubectl get services -n appointments
